#!/bin/bash

ENC="ffmpeg"
ENCPATH=""
OPTS="-c:v libx265 -preset fast -x265-params crf=24 -c:a libvorbis -aq 5 -c:s copy"
SUFFIX="_new.mkv"
SERVERS="localhost"
LEN=60
OUTDIR="$HOME/.dve"
VERBOSE="error"

function usage() {
    cat << EOF
usage: $0 [options] filename

This script breaks a video file up into chunks and encodes them in parallel via SSH on
multiple hosts.

OPTIONS:
    -h  this help message.
    -e  ffmpeg binary to use. (default=${ENC})
    -l  comma separated list of hosts to use to encode. (default=${SERVERS})
    -t  rough length of individual video chunks, in seconds. (default=${MINLEN})
    -o  encoding options. (default=${OPTS})
    -s  output file suffix. (default=${SUFFIX})
    -v  verbose job output. (default=false)
EOF
}

# check all required helper utils
function checkpaths() {
    for cmd in parallel; do
        if ! CMD=`which $cmd`; then
            echo "$cmd not found."
            exit 1
        fi
    done
    # check as absolute path first
    if [ -x "$ENC" ]; then
        ENCPATH="$ENC"
    else
        # then check for something in $PATH
        ENCPATH="`which $ENC`"
        if ! [ -x "$ENCPATH" ]; then
            echo "$ENC not found."
            exit 1
        fi
    fi
}

checkpaths

while getopts “he:l:t:o:s:v” OPTION; do
    case $OPTION in
    h)
    usage
    exit 1
    ;;
    e)
    ENC="$OPTARG"
    ;;
    l)
    SERVERS="$OPTARG"
    ;;
    t)
    LEN="$OPTARG"
    ;;
    o)
    OPTS="$OPTARG"
    ;;
    s)
    SUFFIX="$OPTARG"
    ;;
    v)
    VERBOSE="info"
    ;;
    ?)
    usage
    exit
    ;;
    esac
done
shift $((OPTIND-1))

if [ $# -lt 1 ]; then
    usage
    exit 1
fi

if ! mkdir -p ${OUTDIR}; then
    echo "Couldn't create temp chunk output dir ${OUTDIR}."
    exit 1
fi

echo "Creating chunks to encode"
$ENCPATH -i "$1"  -map 0 -codec copy -f segment -segment_time $LEN -segment_format matroska -v ${VERBOSE} "${OUTDIR}/chunk-%03d.orig"

CWD=`pwd`
cd "$OUTDIR"

echo "Running parallel encoding jobs"
PAR_OPTS="--gnu -j 1 -S ${SERVERS} --eta --retries 2 --nice 10"
#PAR_OPTS="$PAR_OPTS --workdir ... --trc {.}.enc"
PAR_OPTS="$PAR_OPTS --workdir ... --transfer --return {.}.enc"
ENC_OPTS="-y -v ${VERBOSE} -i {} ${OPTS} -f matroska {.}.enc"

echo "parallel ${PAR_OPTS} ${ENCPATH} ${ENC_OPTS} ::: chunk-*.orig"
parallel ${PAR_OPTS} ${ENCPATH} ${ENC_OPTS} ::: chunk-*.orig

echo "Combining chunks into final video file"
echo "ffconcat version 1.0" > concat.txt
for f in `ls chunk-*.enc | sort`; do
    echo "file $f" >> concat.txt
done
BASE=`basename "$1"`
OUTFILE="${CWD}"/"${BASE%.*}${SUFFIX}"
${ENCPATH} -y -v ${VERBOSE} -f concat -i concat.txt -f matroska -map 0 -c copy "${OUTFILE}"

echo "Cleaning up temporary working files"
rm -f "${OUTDIR}"/*
cd "$CWD"
